import LeanForControl.LinearSystems.Realization.Minimality
import Mathlib.LinearAlgebra.Isomorphisms
import Architect

/-!
# Uniqueness of minimal realizations

This file constructs the canonical state equivalence between controllable,
observable realizations with the same Markov behavior.  Both state spaces are
identified with the quotient of the finite input-history space by the kernel
of their controllability maps.  Equality of those kernels follows from the
common finite Hankel matrix and observability.

Reference: Hespanha, *Linear Systems Theory*, §17.3.
-/

namespace LinearSystems

open Matrix

namespace Realization

variable {𝕜 : Type*} [Field 𝕜]
variable {n m p : ℕ}

/-- The state map from a length-`n` input history, represented by the
state-horizon controllability matrix.

Original: quotient construction infrastructure for LeanForControl. -/
def controllabilityMap (R : Realization 𝕜 n m p) :
    (Fin n × Fin m → 𝕜) →ₗ[𝕜] (Fin n → 𝕜) :=
  (controllabilityMatrix R.A R.B).mulVecLin

/-- Controllability is equivalent to surjectivity of the realization's
finite input-history map.

Reference: Hespanha, *Linear Systems Theory*, §17.3. -/
theorem controllabilityMap_surjective (R : Realization 𝕜 n m p)
    (hctrl : R.IsControllable) :
    Function.Surjective R.controllabilityMap := by
  simpa [controllabilityMap] using
    (MatrixAlgebra.mulVec_range_top_iff_rank_eq_card_rows
      (controllabilityMatrix R.A R.B)).mpr (by
        simpa using
          (isControllable_iff_controllabilityMatrix_rank_eq R.A R.B).mp
            hctrl)

/-- Behaviorally equivalent observable realizations of the same dimension
have the same null input histories.

The proof applies the common state-horizon Hankel matrix to a history.  Since
each observability matrix is injective, the Hankel kernel is exactly the
controllability-map kernel.

Reference: Hespanha, *Linear Systems Theory*, §17.3. -/
theorem controllabilityMap_ker_eq_of_observable
    (R₁ R₂ : Realization 𝕜 n m p)
    (hobs₁ : R₁.IsObservable) (hobs₂ : R₂.IsObservable)
    (hbehavior : R₁.BehaviorallyEquivalent R₂) :
    LinearMap.ker R₁.controllabilityMap =
      LinearMap.ker R₂.controllabilityMap := by
  ext u
  constructor
  · intro hu
    rw [LinearMap.mem_ker] at hu ⊢
    apply
      (isObservable_iff_observabilityMatrix_ker_trivial R₂.A R₂.C).mp
        hobs₂
    change
      observabilityMatrix R₂.A R₂.C *ᵥ
          (controllabilityMatrix R₂.A R₂.B *ᵥ u) = 0
    rw [Matrix.mulVec_mulVec, ← R₂.observabilityHorizon_stateDim,
      ← R₂.controllabilityHorizon_stateDim,
      ← R₂.hankelMatrix_eq_observability_mul_controllability,
      ← hbehavior.hankelMatrix_eq n n,
      R₁.hankelMatrix_eq_observability_mul_controllability,
      R₁.observabilityHorizon_stateDim,
      R₁.controllabilityHorizon_stateDim, ← Matrix.mulVec_mulVec]
    simpa [controllabilityMap] using
      congrArg ((observabilityMatrix R₁.A R₁.C).mulVec) hu
  · intro hu
    rw [LinearMap.mem_ker] at hu ⊢
    apply
      (isObservable_iff_observabilityMatrix_ker_trivial R₁.A R₁.C).mp
        hobs₁
    change
      observabilityMatrix R₁.A R₁.C *ᵥ
          (controllabilityMatrix R₁.A R₁.B *ᵥ u) = 0
    rw [Matrix.mulVec_mulVec, ← R₁.observabilityHorizon_stateDim,
      ← R₁.controllabilityHorizon_stateDim,
      ← R₁.hankelMatrix_eq_observability_mul_controllability,
      hbehavior.hankelMatrix_eq n n,
      R₂.hankelMatrix_eq_observability_mul_controllability,
      R₂.observabilityHorizon_stateDim,
      R₂.controllabilityHorizon_stateDim, ← Matrix.mulVec_mulVec]
    simpa [controllabilityMap] using
      congrArg ((observabilityMatrix R₂.A R₂.C).mulVec) hu

/-- The canonical state equivalence induced by equal kernels of the two
surjective controllability maps.

Reference: Hespanha, *Linear Systems Theory*, §17.3. -/
noncomputable def stateEquivOfControllableObservable
    (R₁ R₂ : Realization 𝕜 n m p)
    (hctrl₁ : R₁.IsControllable) (hctrl₂ : R₂.IsControllable)
    (hobs₁ : R₁.IsObservable) (hobs₂ : R₂.IsObservable)
    (hbehavior : R₁.BehaviorallyEquivalent R₂) :
    (Fin n → 𝕜) ≃ₗ[𝕜] (Fin n → 𝕜) :=
  (R₁.controllabilityMap.quotKerEquivOfSurjective
      (R₁.controllabilityMap_surjective hctrl₁)).symm
    |>.trans
      (Submodule.quotEquivOfEq _ _
        (R₁.controllabilityMap_ker_eq_of_observable R₂ hobs₁ hobs₂
          hbehavior))
    |>.trans
      (R₂.controllabilityMap.quotKerEquivOfSurjective
        (R₂.controllabilityMap_surjective hctrl₂))

/-- The canonical state equivalence sends the state generated by an input
history in the first realization to the state generated by the same history
in the second realization.

Original: quotient construction infrastructure for LeanForControl. -/
@[simp]
theorem stateEquivOfControllableObservable_apply_controllabilityMap
    (R₁ R₂ : Realization 𝕜 n m p)
    (hctrl₁ : R₁.IsControllable) (hctrl₂ : R₂.IsControllable)
    (hobs₁ : R₁.IsObservable) (hobs₂ : R₂.IsObservable)
    (hbehavior : R₁.BehaviorallyEquivalent R₂)
    (u : Fin n × Fin m → 𝕜) :
    stateEquivOfControllableObservable R₁ R₂ hctrl₁ hctrl₂ hobs₁ hobs₂
        hbehavior (R₁.controllabilityMap u) =
      R₂.controllabilityMap u := by
  simp [stateEquivOfControllableObservable]

/-- Equal Markov behavior makes every output-power row act identically on
matching finite input histories.

Original: finite-history calculation for LeanForControl. -/
theorem outputPow_mul_controllabilityMatrix_eq
    (R₁ R₂ : Realization 𝕜 n m p)
    (hbehavior : R₁.BehaviorallyEquivalent R₂) (j : ℕ) :
    (R₁.C * R₁.A ^ j) * controllabilityMatrix R₁.A R₁.B =
      (R₂.C * R₂.A ^ j) * controllabilityMatrix R₂.A R₂.B := by
  ext i kj
  obtain ⟨k, l⟩ := kj
  have h := congrArg (fun M => M i l) (hbehavior.2 (j + (k : ℕ)))
  calc
    ((R₁.C * R₁.A ^ j) * controllabilityMatrix R₁.A R₁.B) i (k, l) =
        ((R₁.C * R₁.A ^ j) * (R₁.A ^ (k : ℕ) * R₁.B)) i l := by
          simp only [Matrix.mul_apply, controllabilityMatrix, Matrix.of_apply]
    _ = (R₁.C * R₁.A ^ (j + (k : ℕ)) * R₁.B) i l := by
      rw [pow_add]
      simp only [Matrix.mul_assoc]
    _ = (R₂.C * R₂.A ^ (j + (k : ℕ)) * R₂.B) i l := h
    _ = ((R₂.C * R₂.A ^ j) * (R₂.A ^ (k : ℕ) * R₂.B)) i l := by
      rw [pow_add]
      simp only [Matrix.mul_assoc]
    _ = ((R₂.C * R₂.A ^ j) *
        controllabilityMatrix R₂.A R₂.B) i (k, l) := by
          simp only [Matrix.mul_apply, controllabilityMatrix, Matrix.of_apply]

/-- The canonical state equivalence preserves every future output:
`C₂ A₂^j (T x) = C₁ A₁^j x`.

Reference: Hespanha, *Linear Systems Theory*, §17.3. -/
theorem outputPow_mulVec_stateEquivOfControllableObservable
    (R₁ R₂ : Realization 𝕜 n m p)
    (hctrl₁ : R₁.IsControllable) (hctrl₂ : R₂.IsControllable)
    (hobs₁ : R₁.IsObservable) (hobs₂ : R₂.IsObservable)
    (hbehavior : R₁.BehaviorallyEquivalent R₂)
    (j : ℕ) (x : Fin n → 𝕜) :
    (R₂.C * R₂.A ^ j) *ᵥ
        (stateEquivOfControllableObservable R₁ R₂ hctrl₁ hctrl₂ hobs₁
          hobs₂ hbehavior x) =
      (R₁.C * R₁.A ^ j) *ᵥ x := by
  obtain ⟨u, rfl⟩ := R₁.controllabilityMap_surjective hctrl₁ x
  rw [stateEquivOfControllableObservable_apply_controllabilityMap]
  change
    (R₂.C * R₂.A ^ j) *ᵥ
        (controllabilityMatrix R₂.A R₂.B *ᵥ u) =
      (R₁.C * R₁.A ^ j) *ᵥ
        (controllabilityMatrix R₁.A R₁.B *ᵥ u)
  rw [Matrix.mulVec_mulVec, Matrix.mulVec_mulVec,
    ← outputPow_mul_controllabilityMatrix_eq R₁ R₂ hbehavior j]

/-- The canonical state equivalence intertwines the output matrices.

Reference: Hespanha, *Linear Systems Theory*, §17.3. -/
theorem output_mulVec_stateEquivOfControllableObservable
    (R₁ R₂ : Realization 𝕜 n m p)
    (hctrl₁ : R₁.IsControllable) (hctrl₂ : R₂.IsControllable)
    (hobs₁ : R₁.IsObservable) (hobs₂ : R₂.IsObservable)
    (hbehavior : R₁.BehaviorallyEquivalent R₂)
    (x : Fin n → 𝕜) :
    R₂.C *ᵥ
        (stateEquivOfControllableObservable R₁ R₂ hctrl₁ hctrl₂ hobs₁
          hobs₂ hbehavior x) =
      R₁.C *ᵥ x := by
  simpa using
    outputPow_mulVec_stateEquivOfControllableObservable R₁ R₂ hctrl₁
      hctrl₂ hobs₁ hobs₂ hbehavior 0 x

/-- The canonical state equivalence intertwines the input matrices.

Reference: Hespanha, *Linear Systems Theory*, §17.3. -/
theorem stateEquivOfControllableObservable_input
    (R₁ R₂ : Realization 𝕜 n m p)
    (hctrl₁ : R₁.IsControllable) (hctrl₂ : R₂.IsControllable)
    (hobs₁ : R₁.IsObservable) (hobs₂ : R₂.IsObservable)
    (hbehavior : R₁.BehaviorallyEquivalent R₂)
    (u : Fin m → 𝕜) :
    stateEquivOfControllableObservable R₁ R₂ hctrl₁ hctrl₂ hobs₁ hobs₂
        hbehavior (R₁.B *ᵥ u) =
      R₂.B *ᵥ u := by
  rw [← sub_eq_zero]
  apply hobs₂
  intro k
  rw [Matrix.mulVec_sub,
    outputPow_mulVec_stateEquivOfControllableObservable R₁ R₂ hctrl₁
      hctrl₂ hobs₁ hobs₂ hbehavior (k : ℕ) (R₁.B *ᵥ u)]
  rw [Matrix.mulVec_mulVec, Matrix.mulVec_mulVec, sub_eq_zero]
  exact congrArg (fun M => M *ᵥ u) (hbehavior.2 (k : ℕ))

/-- The canonical state equivalence intertwines the state matrices.

The all-powers output identity shows that the intertwining defect is
unobservable; observability forces it to vanish.

Reference: Hespanha, *Linear Systems Theory*, §17.3. -/
theorem stateEquivOfControllableObservable_state
    (R₁ R₂ : Realization 𝕜 n m p)
    (hctrl₁ : R₁.IsControllable) (hctrl₂ : R₂.IsControllable)
    (hobs₁ : R₁.IsObservable) (hobs₂ : R₂.IsObservable)
    (hbehavior : R₁.BehaviorallyEquivalent R₂)
    (x : Fin n → 𝕜) :
    stateEquivOfControllableObservable R₁ R₂ hctrl₁ hctrl₂ hobs₁ hobs₂
        hbehavior (R₁.A *ᵥ x) =
      R₂.A *ᵥ
        (stateEquivOfControllableObservable R₁ R₂ hctrl₁ hctrl₂ hobs₁
          hobs₂ hbehavior x) := by
  rw [← sub_eq_zero]
  apply hobs₂
  intro k
  rw [Matrix.mulVec_sub,
    outputPow_mulVec_stateEquivOfControllableObservable R₁ R₂ hctrl₁
      hctrl₂ hobs₁ hobs₂ hbehavior (k : ℕ) (R₁.A *ᵥ x)]
  rw [Matrix.mulVec_mulVec, Matrix.mulVec_mulVec, sub_eq_zero]
  have hfuture :=
    outputPow_mulVec_stateEquivOfControllableObservable R₁ R₂ hctrl₁
      hctrl₂ hobs₁ hobs₂ hbehavior ((k : ℕ) + 1) x
  simpa [pow_succ, Matrix.mul_assoc] using hfuture.symm

/-- Controllable, observable, behaviorally equivalent realizations of the
same state dimension are similar.

The similarity matrix is the standard-basis matrix of the canonical quotient
state equivalence.

Reference: Hespanha, *Linear Systems Theory*, §17.3. -/
noncomputable def similarOfIsControllableOfIsObservableOfBehaviorallyEquivalent
    (R₁ R₂ : Realization 𝕜 n m p)
    (hctrl₁ : R₁.IsControllable) (hobs₁ : R₁.IsObservable)
    (hctrl₂ : R₂.IsControllable) (hobs₂ : R₂.IsObservable)
    (hbehavior : R₁.BehaviorallyEquivalent R₂) :
    Similar R₁ R₂ := by
  let e :=
    stateEquivOfControllableObservable R₁ R₂ hctrl₁ hctrl₂ hobs₁ hobs₂
      hbehavior
  refine
    { T := e.toLinearMap.toMatrix'
      Tinv := e.symm.toLinearMap.toMatrix'
      Tinv_mul_T := ?_
      T_mul_Tinv := ?_
      state := ?_
      input := ?_
      output := ?_
      feedthrough := hbehavior.1.symm }
  · rw [Matrix.ext_iff_mulVec]
    intro x
    rw [← Matrix.mulVec_mulVec]
    simp
  · rw [Matrix.ext_iff_mulVec]
    intro x
    rw [← Matrix.mulVec_mulVec]
    simp
  · rw [Matrix.ext_iff_mulVec]
    intro x
    rw [← Matrix.mulVec_mulVec, ← Matrix.mulVec_mulVec]
    simp only [LinearMap.toMatrix'_mulVec]
    exact
      (stateEquivOfControllableObservable_state R₁ R₂ hctrl₁ hctrl₂
        hobs₁ hobs₂ hbehavior x).symm
  · rw [Matrix.ext_iff_mulVec]
    intro u
    rw [← Matrix.mulVec_mulVec]
    simp only [LinearMap.toMatrix'_mulVec]
    exact
      (stateEquivOfControllableObservable_input R₁ R₂ hctrl₁ hctrl₂
        hobs₁ hobs₂ hbehavior u).symm
  · rw [Matrix.ext_iff_mulVec]
    intro x
    rw [← Matrix.mulVec_mulVec]
    simp only [LinearMap.toMatrix'_mulVec]
    exact
      output_mulVec_stateEquivOfControllableObservable R₁ R₂ hctrl₁ hctrl₂
        hobs₁ hobs₂ hbehavior x

/-- Behaviorally equivalent minimal realizations with the same indexed state
dimension are similar.

Reference: Hespanha, *Linear Systems Theory*, §17.3. -/
noncomputable def similarOfIsMinimalOfBehaviorallyEquivalent
    (R₁ R₂ : Realization ℂ n m p)
    (hmin₁ : R₁.IsMinimal) (hmin₂ : R₂.IsMinimal)
    (hbehavior : R₁.BehaviorallyEquivalent R₂) :
    Similar R₁ R₂ := by
  have h₁ := (isMinimal_iff_isControllable_and_isObservable R₁).mp hmin₁
  have h₂ := (isMinimal_iff_isControllable_and_isObservable R₂).mp hmin₂
  exact
    similarOfIsControllableOfIsObservableOfBehaviorallyEquivalent
      R₁ R₂ h₁.1 h₁.2 h₂.1 h₂.2 hbehavior

/-- Controllable, observable, behaviorally equivalent realizations of the
same state dimension admit a similarity witness.

Reference: Hespanha, *Linear Systems Theory*, §17.3. -/
@[blueprint "thm:controllable-observable-behaviorally-equivalent-similar"
  (statement := /-- Two controllable and observable realizations with the
    same Markov behavior are related by an invertible change of state
    coordinates. -/)]
theorem similar_of_isControllable_of_isObservable_of_behaviorallyEquivalent
    (R₁ R₂ : Realization 𝕜 n m p)
    (hctrl₁ : R₁.IsControllable) (hobs₁ : R₁.IsObservable)
    (hctrl₂ : R₂.IsControllable) (hobs₂ : R₂.IsObservable)
    (hbehavior : R₁.BehaviorallyEquivalent R₂) :
    Nonempty (Similar R₁ R₂) :=
  ⟨similarOfIsControllableOfIsObservableOfBehaviorallyEquivalent
    R₁ R₂ hctrl₁ hobs₁ hctrl₂ hobs₂ hbehavior⟩

/-- Behaviorally equivalent minimal realizations with the same indexed state
dimension admit a similarity witness.

Reference: Hespanha, *Linear Systems Theory*, §17.3. -/
@[blueprint "thm:minimal-realizations-unique-up-to-similarity"
  (statement := /-- Minimal realizations of the same finite-dimensional
    behavior are unique up to a change of state coordinates. -/)]
theorem similar_of_isMinimal_of_behaviorallyEquivalent
    (R₁ R₂ : Realization ℂ n m p)
    (hmin₁ : R₁.IsMinimal) (hmin₂ : R₂.IsMinimal)
    (hbehavior : R₁.BehaviorallyEquivalent R₂) :
    Nonempty (Similar R₁ R₂) :=
  ⟨similarOfIsMinimalOfBehaviorallyEquivalent R₁ R₂ hmin₁ hmin₂
    hbehavior⟩

/-- For minimal realizations of a fixed state dimension, behavioral
equivalence is exactly state-space similarity.

Reference: Hespanha, *Linear Systems Theory*, §17.3. -/
theorem behaviorallyEquivalent_iff_similar_of_isMinimal
    (R₁ R₂ : Realization ℂ n m p)
    (hmin₁ : R₁.IsMinimal) (hmin₂ : R₂.IsMinimal) :
    R₁.BehaviorallyEquivalent R₂ ↔ Nonempty (Similar R₁ R₂) := by
  constructor
  · intro h
    exact similar_of_isMinimal_of_behaviorallyEquivalent R₁ R₂ hmin₁ hmin₂ h
  · rintro ⟨h⟩
    exact h.behaviorallyEquivalent R₁ R₂

/-- Minimal behaviorally equivalent realizations of potentially different
state dimensions have equal dimensions and become similar after transport
along that equality.

Reference: Hespanha, *Linear Systems Theory*, §17.3. -/
theorem exists_stateDim_eq_and_similar_of_isMinimal_of_behaviorallyEquivalent
    {n₁ n₂ : ℕ} (R₁ : Realization ℂ n₁ m p)
    (R₂ : Realization ℂ n₂ m p)
    (hmin₁ : R₁.IsMinimal) (hmin₂ : R₂.IsMinimal)
    (hbehavior : R₁.BehaviorallyEquivalent R₂) :
    ∃ h : n₁ = n₂, Nonempty (Similar (h ▸ R₁) R₂) := by
  have hdim := hmin₁.stateDim_eq_of_behaviorallyEquivalent hmin₂ hbehavior
  subst n₂
  exact
    ⟨rfl,
      similar_of_isMinimal_of_behaviorallyEquivalent R₁ R₂ hmin₁ hmin₂
        hbehavior⟩

end Realization

end LinearSystems
